### ISSUE TITLE
Should support multithreaded story execution

### ISSUE THREAD

**Issue by AndreasEK** [valfirst/jbehave-junit-runner#20]
Right now the reporting only works, when JBehave is executing the tests in a single thread. It'd be nice, to allow JBehave to run tests multithreaded - with working reporting to JUnit. 

Implementation idea: put all state in the reporter (currentScenario, etc) in a ThreadLocal context. This should be achieved fairly easily and should work under the assumption that one scenario / story is completely executed in one Thread.

**Comment by dschneller** [comment]
Which holds true, AFAIK, for the current JBehave implementation. So yes, that should work.
This is one of the cases where my current project is absolutely NOT usable as a test subject :-)

**Comment by AndreasEK** [comment]
I have no idea, though, how JUnit behaves, when it received notifications from several threads...

**Comment by dschneller** [comment]
That would probably have to be done through a synchronized "message center" instance, so that from JUnit's point of view everything is still single threaded. As long as the step description strings remain uniquified all that could (and should) happen would probably be some jumping up and down in the JUnit view as reports abour progress come in in non-sequential order.

**Comment by valfirst** [comment]
Done: [Add support of multithreaded story execution](https://github.com/valfirst/jbehave-junit-runner/commit/bcd7d52961a406fe75e9a5ab46a0b2262e94af94)
