### ISSUE TITLE
Jbehave error error reporting.

### ISSUE THREAD

**Issue by GiriMPT** [valfirst/jbehave-junit-runner#26]
Version : 1.0.1
Problem: 
When a step fails jbehave report seem to add '\u200B' at the end of the line in the error report, please see the example as below. Is it because of de.codecentric.jbehave.junit.monitoring.DescriptionTextUniquefier.getUniqueDescription.

com.test.steps.TrainingTest.When I perform a Java training\u200B
com.test.steps.TrainingTest.When I perform a Java training\u200B\u200B
com.test.steps.TrainingTest.When I perform a Java training\u200B\u200B\u200B
com.test.steps.TrainingTest.When I perform a Java training\u200B\u200B\u200B\u200B
com.test.steps.TrainingTest.When I perform a Java training\u200B\u200B\u200B\u200B\u200B
com.test.steps.TrainingTest.When I perform a Java training\u200B\u200B\u200B\u200B\u200B\u200B
com.test.steps.TrainingTest.When I perform a Java training\u200B\u200B\u200B\u200B\u200B\u200B\u200B
com.test.steps.TrainingTest.When I perform a Java training\u200B\u200B\u200B\u200B\u200B\u200B\u200B\u200B
com.test.steps.TrainingTest.When I perform a Java training\u200B\u200B\u200B\u200B\u200B\u200B\u200B\u200B\u200B

Can you please let me know if I am doing anything wrong?. I am using Single threaded tests.

Thanks
Girish

**Comment by AndreasEK** [comment]
Hi,

this is sort of expected behaviour. In JUnit the test cases need to have a unique name, while in JBehave the steps can be executed multiple times. The solution was to append a non-displayable unicode character to the end of a step to give it a unique name. 

How do you display the results that you see the unicode character?

Andreas

**Comment by GiriMPT** [comment]
Hi,

Results are displayed in jenkins.

Girish

**Comment by AndreasEK** [comment]
HI,

I am sorry, but I have no idea how to fix this. JUnit requires tests to have unique names, within the scope of a suite. This is a perfectly valid assumption for JUnit, since method names in a test class ARE unique. However, in a scenario, a step can be used multiple times, so we have to "uniquify" them. That is an awesome word, by the way :)

Sorry for the bad news.
