### ISSUE TITLE
Compiling jbehave-junit-runner for Java 6

### ISSUE THREAD

**Issue by ftomassetti** [valfirst/jbehave-junit-runner#75]
Hi,
we would love to use jbehave-junit-runner in [javaparser](https://github.com/javaparser/javaparser/). The only issue is that we are stuck with Java 6 and it seems that jbehav-junit-runner has been uploaded after being compiled with Java 7. Would it be possible to compile it instead with Java 7? I know it should not be supported anymore but unfortunately we cannot move to Java 7 because a lot of our users are still stuck with Java 6. Is that any reason to use Java 7 (I never understood what are the benefits of Java 7 :D).
Thanks a lot guys!

**Comment by skurlow** [comment]
Hi Federico,

Change the JDK version in the pom.xml to 6 and see if all the tests run ok.
Most likely it will be fine. Then put any changes up in a patch and request
they can be pulled into a new release.

Regards,

[image: Stephen Kurlow on about.me]

Stephen Kurlow
about.me/skurlow
  http://about.me/skurlow

**Comment by ftomassetti** [comment]
Done, as expected to problems running tests. See pull request #76

**Comment by britter** [comment]
This project depends on Java 7 because we don't support Java versions that are EOL. We will not resolve this, because we don't even have Java 6 installed on our machines anymore. Since Java 7 will be OEL this April, it is likely, that we move to Java 8 then.
There are some benefits when using Java 7 compared to Java 6:
- bug fixes
- diamond notation
- multi catch blocks
- switch statements over strings

But think about this: Do libraries have to support old Java versions because users are using old Java versions or do users use old Java versions because libraries still support it? :-)

If you really need a Java 6 compatible version of this library I think you should fork it.

**Comment by ftomassetti** [comment]
Hi Benedikt, I understand your point, I just advocated for Javaparser to move to Java 8 :)
For the time being we will just use an older version of your plugin.

Just for me to better understand: I understand that people should use JDK 8 but I think you can use JDK 8 and compile to the class format of Java 6 (on my machine I have just JDK 8 and I did it). So it means that the users can still compile and use the jars using a modern JDK (benefitting of all the bug fixes). Am I wrong/missing anything?

**Comment by britter** [comment]
Yes you're missing something :-) By compiling with a newer Java version to an older target version, you can run into problems when using APIs that have been introduced in your Java version. 
For example you can use the `java.lang.Objects` class when you're using Java 7 and compile to Java 6. Everything will work fine, but the code will crash when running in a Java 6 environment.

Further more, it won't detect dependencies that use a higher java version. This happend during the release of Apache Commons Validator 1.4.1 for example (http://markmail.org/message/3xpowjysfig5ozky)

Would it be okay for you if we close this?

**Comment by ftomassetti** [comment]
Sure and thank you for the explanation!
And of course also thank you for working on this project, me and the other folks at Javaparser are very happy to use it!
